### ISSUE TITLE
Initial project checklist

### ISSUE THREAD

**Issue by marsmith** [marsmith/Site-Maker-Back-End#1]
**Create fake stream network and precompiled map (run once)**
- [x] Create fake network (sample dataset -- find good section of NHD and clip)
- [x] Create data structure (populate node dataset with upstream data)
- [x] Overlay existing sites and update data structure (there could be issues)
- [x] Store distances and ID's of most upstream at each confluence
